### ISSUE TITLE
How to build and run this mod locally ?

### ISSUE THREAD

**Issue by techhubhub** [hbstack/search#163]
How to build and run this mod locally ?  trying with npm ci and hugo server doesn't work.
also, how does this search compare to https://github.com/hugomods/search ?
let's say we would like to use one of the search as mod, which one you recommend ?

can you give an simple example where 
<img width="1283" alt="image" src="https://github.com/hbstack/search/assets/158099291/2a914ca9-3b55-4803-b209-be3c95bb9fbd">
is display and some simple data for search 

Thank you.

**Comment by razonyang** [comment]
Duplicate to hugomods/search#203
