### ISSUE TITLE
[Feature Request] Add Google Custom Search Engine as fallback

### ISSUE THREAD

**Issue by TetraTheta** [hbstack/search#84]
This module uses [Fuse.js](https://www.fusejs.io/) for its search capability. 

But when I tested it in my localhost environment, it doesn't work well with Korean.
<details>
<summary>Gramatical example of Korean words</summary>

Korean words can be consist of postposition or other words. So a word '밥' which means 'meal' can be '밥을' or '밥도' etc. depending on its location or role on phrase.  
I think Fuse.js can't handle it properly.
</details>

I tried to search '가면 무녀' which is actually in content of post, and content of generated `search.json`. Fuse.js couldn't find any result.  
Of course, I enabled `index_content` to make Fuse.js to search content of my posts.
```yaml
# param.yml
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  expand_results_meta: true
  index_content: true
  # shortcut_search: ["/"]
```
But company like Google should have capability of handling Korean words properly, or they won't have any market share because of poor search engine efficiency.

So I want to integrate Google Custom Search Engine to search modal, not as separate page like `mysite.com/search`.

---

I think integrating Google Custom Search Engine can be done in two ways:

### Just use Google Custom Search Engine

Instead of using Fuse.js, just let Google to handle search.

![1](https://github.com/hbstack/search/assets/37061801/c958b081-6cb2-4014-be86-95db4a6f161d)

There won't be any options under search bar because they aren't needed with Google Custom Search Engine.

### Add button for enabling Google Custom Search Engine

![2](https://github.com/hbstack/search/assets/37061801/563126cf-67ed-4c5e-ab28-64923b7ef06f)

(I re-used icon because I'm lazy)

This will put 'Search with Google' button at the right side of search option panel. If user clicks it, it will render Google Custom Search Engine result in below.

**Comment by razonyang** [comment]
I think it's out of scope of this module, and will make it hard to maintain, it certainly brings new dependencies and increases the size of bundle. I'd like to keep the module as simple as it is.

If I'm planing to support it, it'll be a new module. But as I know, the Google Search JSON API is limited to 100/day for free, see https://developers.google.com/custom-search/v1/overview#pricing. I don't think it will be used by most of clients widely, and it also takes time to implement, so it's no plan on this for now.

**Comment by razonyang** [comment]
Btw, could you please provide an example (content and keyword) to test whether is it an issue of configuration or Fuse.js?

**Comment by TetraTheta** [comment]
> But as I know, the Google Search JSON API is limited to 100/day for free, see https://developers.google.com/custom-search/v1/overview#pricing.

Oh, I should look more carefully on that documentation...

I think I'm just taking a quick look, but what about [Programmable Search Engine](https://developers.google.com/custom-search/docs/overview?hl=en)? If we use 'Standard Search Element' option, I think there isn't any pricing problem with it.

The search is done in client side javascript, and according to documentation
> After creating a Programmable Search Engine, you can use a default page hosted by Google to show your results to the user, or you can embed search functionality directly in your website.

we can embed search result to site directly.

If this is good enough, I will change this Feature Request title to it.

---

> Btw, could you please provide an example (content and keyword) to test whether is it an issue of configuration or Fuse.js?

Is generated `search.json` enough? When I inspected it briefly, I could see the word I wanted to search in that JSON file.

**Comment by TetraTheta** [comment]
If `fuse.js` cannot handle languages other than English, maybe switching to `lunr` might be a good idea.

According to [npm trends](https://npmtrends.com/fuse.js-vs-lunr), people uses `fuse.js` more and `lunr`, but I couldn't find multi-language support information from fuse.js documentation. [An Issue](https://github.com/krisk/Fuse/issues/490) asking about what language is supported by `fuse.js` is closed because of inactivity. I could find other issue/pr for supporting multiple languages but they are all closed.

But I could find `lunr` supports multiple lauguages including Chinese, Korean etc.   
Japanese is supported by `lunr` [by default](https://lunrjs.com/guides/language_support.html). Chinese and Korean can be supported via [`lunr-languages`](https://github.com/MihaiValentin/lunr-languages) which is plugin for `lunr`.

I couldn't test it if it works or not, but I think Chinese and Korean can be supported is crucial part of using it. If something goes wrong, we can create issue for it because they are _supported_.

**Comment by razonyang** [comment]
> I think I'm just taking a quick look, but what about [Programmable Search Engine](https://developers.google.com/custom-search/docs/overview?hl=en)? If we use 'Standard Search Element' option, I think there isn't any pricing problem with it.

It's ok to support using built-in UI of custom Google search engine, but there are styles work need to be fixed, I'm happy to create a skeleton module for this if you're willing to help to fix the style.

For now, you can simply creating a menu to open the Google-hosted custom search engine page, it should suit your needs, but if you want to embed the search results, we should fix the conflict styles between Bootstrap and custom search engine,  especially it look very ugly on the dark mode.

> If `fuse.js` cannot handle languages other than English, maybe switching to `lunr` might be a good idea.

No, this project will stick with Fuse.js, it works well with English and Chinese. I tested on [one of Korean sites using this theme](https://evanote.mew.kr) as well, it should work. I don't see any reasons to swith to Lunr, you can rewrite the engine part with Lunr if you want via forking the project and creating your own.

![image](https://github.com/hbstack/search/assets/17720932/c93c027f-f68e-4e07-a8ee-2800c751fe4f)

I don't understand Korean at all, so if you're talking the advanced words segmentations in your use case, I don't think that client-side search via Fuse.js or Lunr can help.

**Comment by TetraTheta** [comment]
> tested on [one of Korean sites using this theme](https://evanote.mew.kr/) as well, it should work.

Here are some cases which `fuse.js` cannot search terms correctly.

![1](https://github.com/hbstack/search/assets/37061801/5a6951bc-728c-421e-9169-fbab153072b9)

I will try to search '코딩 툴', and '마이크로소프트' in that site.

![2](https://github.com/hbstack/search/assets/37061801/e2947611-7c70-4c6a-90f2-ea44d694adcf)

Searching with '코딩 툴' Fails.

![3](https://github.com/hbstack/search/assets/37061801/7c41eddb-86ef-43b7-945a-35513dd1bd3e)

Searching with '마이크로소프트' also fails.

![4](https://github.com/hbstack/search/assets/37061801/6a111a3b-8ce1-4b9a-8990-1f910b4868d9)

Searching 'Visual Studio' works.

![5](https://github.com/hbstack/search/assets/37061801/1457c6f3-99be-45b0-9c2a-86bafdf82f64)

Even partial search, with 'vis' works too.

![6](https://github.com/hbstack/search/assets/37061801/28c669d4-e18a-4e5f-a760-df8459e5b022)

Searching only with '툴' doesn't work.

---

My conclusion is `fuse.js` cannot handle Korean words.

> it works well with English and Chinese

My guess is, both language phrase can be 'tokenized' with space character. But in Korean, each segments separated by space can be separacted further. 

For example, segment '마이크로소프트에서' can be splitted by '마이크로소프트' and '에서'. In `lunr`, I think `에서` will be ignored by 'stop word filter' because it is postposition.

**Comment by razonyang** [comment]
You should tweak the [parameters](https://hugomods.com/en/search/configurations/#site-parameters) to suit your needs.
1. `min_match_char_length`, how many chars can be considered as a valid keyword.
2. `index_content` should be enabled if you want to search text from the whole article, you'll need to tweak the [distance](https://hugomods.com/en/search/configurations/#distance), [location](https://hugomods.com/en/search/configurations/#location) and [threshold](https://hugomods.com/en/search/configurations/#threshold) as well, you can simply disable the location via [ignore_location](https://hugomods.com/en/search/configurations/#ignore_location).

I just copy and paste partial content for testing locally, work as expected.

![image](https://github.com/hbstack/search/assets/17720932/5cf590a9-fa24-4555-b49e-6873828be5e8)

![image](https://github.com/hbstack/search/assets/17720932/aeb5b5ae-da03-4d6a-81f8-40271464a8fb)

![image](https://github.com/hbstack/search/assets/17720932/9eb78e75-b514-467a-ae74-a3ab177f45fb)

**Comment by TetraTheta** [comment]
So the reason I couldn't find search result about '툴' was `min_match_char_length: 2`.  
But setting it to `min_match_char_length: 1` will cause postpositions to be included in search result, which I don't want that happen.

```yml
search:
  case_sensitive: false
  distance: 1000 # ignored by 'ignore_location'
  expand_results_meta: true
  ignore_location: true
  index_content: true
  location: 10 # ignored by 'ignore_location'
  min_match_char_length: 2
  stall_threshold: 900
  threshold: 0.2
```
I will tweak parameters of `search` more. Like you said before, if I can't be satisfied with `fuse.js`, I will try to implement my own search thingy.

Thank you, and apologize for my dumbness! I should've read [docs](https://hugomods.com/en/docs/search) more carefully...

**Comment by razonyang** [comment]
@TetraTheta FYI, the GCSE module is availale now: https://hbstack.dev/en/modules/header/gcse/.

**Comment by TetraTheta** [comment]
Thank you for letting me know about it!
